environment:
  JAVA_HOME : C:\Program Files\Java\jdk1.7.0\

# os: Visual Studio 2015

install:
  - dir C:\Program Files (x86)\nodejs\
  - ps: Install-Product node 6 x86
  - mvn install -DskipTests=true -Dgpg.skip=true

test_script:
  - mvn test 

build: off